package com.alipay.account.common.dal.auto.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class AccountDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_number
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String accountNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_name
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_type
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.currency
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.balance
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.status
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.gmt_create
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.gmt_modified
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.desc
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_relation_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String accRelationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_id
     *
     * @return the value of account.account_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_id
     *
     * @param accountId the value for account.account_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_number
     *
     * @return the value of account.account_number
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_number
     *
     * @param accountNumber the value for account.account_number
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_name
     *
     * @return the value of account.account_name
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_name
     *
     * @param accountName the value for account.account_name
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_type
     *
     * @return the value of account.account_type
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_type
     *
     * @param accountType the value for account.account_type
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.currency
     *
     * @return the value of account.currency
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.currency
     *
     * @param currency the value for account.currency
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.balance
     *
     * @return the value of account.balance
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.balance
     *
     * @param balance the value for account.balance
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.status
     *
     * @return the value of account.status
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.status
     *
     * @param status the value for account.status
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.gmt_create
     *
     * @return the value of account.gmt_create
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.gmt_create
     *
     * @param gmtCreate the value for account.gmt_create
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.gmt_modified
     *
     * @return the value of account.gmt_modified
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.gmt_modified
     *
     * @param gmtModified the value for account.gmt_modified
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.desc
     *
     * @return the value of account.desc
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.desc
     *
     * @param desc the value for account.desc
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_relation_id
     *
     * @return the value of account.acc_relation_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getAccRelationId() {
        return accRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_relation_id
     *
     * @param accRelationId the value for account.acc_relation_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setAccRelationId(String accRelationId) {
        this.accRelationId = accRelationId;
    }
}