package com.alipay.account.common.dal.auto.daointerface;

import com.alipay.account.common.dal.auto.dataobject.AccountTransactionDO;
import com.alipay.account.common.dal.auto.dataobject.AccountTransactionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountTransactionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    long countByExample(AccountTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int deleteByExample(AccountTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int deleteByPrimaryKey(String txnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int insert(AccountTransactionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int insertSelective(AccountTransactionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    List<AccountTransactionDO> selectByExample(AccountTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    AccountTransactionDO selectByPrimaryKey(String txnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int updateByExampleSelective(@Param("row") AccountTransactionDO row, @Param("example") AccountTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int updateByExample(@Param("row") AccountTransactionDO row, @Param("example") AccountTransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int updateByPrimaryKeySelective(AccountTransactionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int updateByPrimaryKey(AccountTransactionDO row);
}