package com.alipay.account.common.dal.auto.daointerface;

import com.alipay.account.common.dal.auto.dataobject.LedgerEntryDO;
import com.alipay.account.common.dal.auto.dataobject.LedgerEntryDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LedgerEntryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    long countByExample(LedgerEntryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int deleteByExample(LedgerEntryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int deleteByPrimaryKey(Long ledgerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int insert(LedgerEntryDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int insertSelective(LedgerEntryDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    List<LedgerEntryDO> selectByExample(LedgerEntryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    LedgerEntryDO selectByPrimaryKey(Long ledgerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int updateByExampleSelective(@Param("row") LedgerEntryDO row, @Param("example") LedgerEntryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int updateByExample(@Param("row") LedgerEntryDO row, @Param("example") LedgerEntryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int updateByPrimaryKeySelective(LedgerEntryDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_entry
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    int updateByPrimaryKey(LedgerEntryDO row);
}