package com.alipay.account_center.common.dal.auto.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class AccountTransactionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.txn_id
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private String txnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.gmt_create
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.gmt_modified
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.gmt_complete
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private Date gmtComplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.payer_account_id
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private String payerAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.payee_account_id
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private String payeeAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.amount
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.currency
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.type
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.status
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.failure_reason
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private String failureReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.desc
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.direction
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    private String direction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.txn_id
     *
     * @return the value of transaction.txn_id
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.txn_id
     *
     * @param txnId the value for transaction.txn_id
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setTxnId(String txnId) {
        this.txnId = txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.gmt_create
     *
     * @return the value of transaction.gmt_create
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.gmt_create
     *
     * @param gmtCreate the value for transaction.gmt_create
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.gmt_modified
     *
     * @return the value of transaction.gmt_modified
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.gmt_modified
     *
     * @param gmtModified the value for transaction.gmt_modified
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.gmt_complete
     *
     * @return the value of transaction.gmt_complete
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public Date getGmtComplete() {
        return gmtComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.gmt_complete
     *
     * @param gmtComplete the value for transaction.gmt_complete
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setGmtComplete(Date gmtComplete) {
        this.gmtComplete = gmtComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.payer_account_id
     *
     * @return the value of transaction.payer_account_id
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public String getPayerAccountId() {
        return payerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.payer_account_id
     *
     * @param payerAccountId the value for transaction.payer_account_id
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setPayerAccountId(String payerAccountId) {
        this.payerAccountId = payerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.payee_account_id
     *
     * @return the value of transaction.payee_account_id
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public String getPayeeAccountId() {
        return payeeAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.payee_account_id
     *
     * @param payeeAccountId the value for transaction.payee_account_id
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setPayeeAccountId(String payeeAccountId) {
        this.payeeAccountId = payeeAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.amount
     *
     * @return the value of transaction.amount
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.amount
     *
     * @param amount the value for transaction.amount
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.currency
     *
     * @return the value of transaction.currency
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.currency
     *
     * @param currency the value for transaction.currency
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.type
     *
     * @return the value of transaction.type
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.type
     *
     * @param type the value for transaction.type
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.status
     *
     * @return the value of transaction.status
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.status
     *
     * @param status the value for transaction.status
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.failure_reason
     *
     * @return the value of transaction.failure_reason
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public String getFailureReason() {
        return failureReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.failure_reason
     *
     * @param failureReason the value for transaction.failure_reason
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.desc
     *
     * @return the value of transaction.desc
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.desc
     *
     * @param desc the value for transaction.desc
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.direction
     *
     * @return the value of transaction.direction
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.direction
     *
     * @param direction the value for transaction.direction
     *
     * @mbg.generated Thu Mar 12 00:52:54 AEDT 2026
     */
    public void setDirection(String direction) {
        this.direction = direction;
    }
}