package com.alipay.account_center.common.dal.auto.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class LedgerEntryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.ledger_id
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private Long ledgerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.txn_id
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private String txnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.account_id
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.entry_type
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private String entryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.amount
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.currency
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.balance_after
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private BigDecimal balanceAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.status
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.gmt_create
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.gmt_modified
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_entry.remark
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.ledger_id
     *
     * @return the value of ledger_entry.ledger_id
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public Long getLedgerId() {
        return ledgerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.ledger_id
     *
     * @param ledgerId the value for ledger_entry.ledger_id
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setLedgerId(Long ledgerId) {
        this.ledgerId = ledgerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.txn_id
     *
     * @return the value of ledger_entry.txn_id
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.txn_id
     *
     * @param txnId the value for ledger_entry.txn_id
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setTxnId(String txnId) {
        this.txnId = txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.account_id
     *
     * @return the value of ledger_entry.account_id
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.account_id
     *
     * @param accountId the value for ledger_entry.account_id
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.entry_type
     *
     * @return the value of ledger_entry.entry_type
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public String getEntryType() {
        return entryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.entry_type
     *
     * @param entryType the value for ledger_entry.entry_type
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setEntryType(String entryType) {
        this.entryType = entryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.amount
     *
     * @return the value of ledger_entry.amount
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.amount
     *
     * @param amount the value for ledger_entry.amount
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.currency
     *
     * @return the value of ledger_entry.currency
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.currency
     *
     * @param currency the value for ledger_entry.currency
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.balance_after
     *
     * @return the value of ledger_entry.balance_after
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public BigDecimal getBalanceAfter() {
        return balanceAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.balance_after
     *
     * @param balanceAfter the value for ledger_entry.balance_after
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setBalanceAfter(BigDecimal balanceAfter) {
        this.balanceAfter = balanceAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.status
     *
     * @return the value of ledger_entry.status
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.status
     *
     * @param status the value for ledger_entry.status
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.gmt_create
     *
     * @return the value of ledger_entry.gmt_create
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.gmt_create
     *
     * @param gmtCreate the value for ledger_entry.gmt_create
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.gmt_modified
     *
     * @return the value of ledger_entry.gmt_modified
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.gmt_modified
     *
     * @param gmtModified the value for ledger_entry.gmt_modified
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_entry.remark
     *
     * @return the value of ledger_entry.remark
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_entry.remark
     *
     * @param remark the value for ledger_entry.remark
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}