package com.alipay.account_center.common.dal.auto.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class TransactionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.txn_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String txnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.gmt_create
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.gmt_modified
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.gmt_complete
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private Date gmtComplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.payer_account_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String payerAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.payee_account_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String payeeAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.amount
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.currency
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.type
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.status
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.failure_reason
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String failureReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.ext_info
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.category
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.reference_type
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String referenceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.reference_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    private String referenceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.txn_id
     *
     * @return the value of transaction.txn_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.txn_id
     *
     * @param txnId the value for transaction.txn_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setTxnId(String txnId) {
        this.txnId = txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.gmt_create
     *
     * @return the value of transaction.gmt_create
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.gmt_create
     *
     * @param gmtCreate the value for transaction.gmt_create
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.gmt_modified
     *
     * @return the value of transaction.gmt_modified
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.gmt_modified
     *
     * @param gmtModified the value for transaction.gmt_modified
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.gmt_complete
     *
     * @return the value of transaction.gmt_complete
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public Date getGmtComplete() {
        return gmtComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.gmt_complete
     *
     * @param gmtComplete the value for transaction.gmt_complete
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setGmtComplete(Date gmtComplete) {
        this.gmtComplete = gmtComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.payer_account_id
     *
     * @return the value of transaction.payer_account_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getPayerAccountId() {
        return payerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.payer_account_id
     *
     * @param payerAccountId the value for transaction.payer_account_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setPayerAccountId(String payerAccountId) {
        this.payerAccountId = payerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.payee_account_id
     *
     * @return the value of transaction.payee_account_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getPayeeAccountId() {
        return payeeAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.payee_account_id
     *
     * @param payeeAccountId the value for transaction.payee_account_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setPayeeAccountId(String payeeAccountId) {
        this.payeeAccountId = payeeAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.amount
     *
     * @return the value of transaction.amount
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.amount
     *
     * @param amount the value for transaction.amount
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.currency
     *
     * @return the value of transaction.currency
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.currency
     *
     * @param currency the value for transaction.currency
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.type
     *
     * @return the value of transaction.type
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.type
     *
     * @param type the value for transaction.type
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.status
     *
     * @return the value of transaction.status
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.status
     *
     * @param status the value for transaction.status
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.failure_reason
     *
     * @return the value of transaction.failure_reason
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getFailureReason() {
        return failureReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.failure_reason
     *
     * @param failureReason the value for transaction.failure_reason
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.ext_info
     *
     * @return the value of transaction.ext_info
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.ext_info
     *
     * @param extInfo the value for transaction.ext_info
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.category
     *
     * @return the value of transaction.category
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.category
     *
     * @param category the value for transaction.category
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.reference_type
     *
     * @return the value of transaction.reference_type
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getReferenceType() {
        return referenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.reference_type
     *
     * @param referenceType the value for transaction.reference_type
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setReferenceType(String referenceType) {
        this.referenceType = referenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.reference_id
     *
     * @return the value of transaction.reference_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.reference_id
     *
     * @param referenceId the value for transaction.reference_id
     *
     * @mbg.generated Mon Jun 29 17:20:06 AEST 2026
     */
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }
}