package com.alipay.alipay_plus.common.dal.auto.dataobject;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccountTransactionDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public AccountTransactionDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTxnIdIsNull() {
            addCriterion("txn_id is null");
            return (Criteria) this;
        }

        public Criteria andTxnIdIsNotNull() {
            addCriterion("txn_id is not null");
            return (Criteria) this;
        }

        public Criteria andTxnIdEqualTo(String value) {
            addCriterion("txn_id =", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotEqualTo(String value) {
            addCriterion("txn_id <>", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdGreaterThan(String value) {
            addCriterion("txn_id >", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdGreaterThanOrEqualTo(String value) {
            addCriterion("txn_id >=", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdLessThan(String value) {
            addCriterion("txn_id <", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdLessThanOrEqualTo(String value) {
            addCriterion("txn_id <=", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdLike(String value) {
            addCriterion("txn_id like", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotLike(String value) {
            addCriterion("txn_id not like", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdIn(List<String> values) {
            addCriterion("txn_id in", values, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotIn(List<String> values) {
            addCriterion("txn_id not in", values, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdBetween(String value1, String value2) {
            addCriterion("txn_id between", value1, value2, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotBetween(String value1, String value2) {
            addCriterion("txn_id not between", value1, value2, "txnId");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteIsNull() {
            addCriterion("gmt_complete is null");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteIsNotNull() {
            addCriterion("gmt_complete is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteEqualTo(Date value) {
            addCriterion("gmt_complete =", value, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteNotEqualTo(Date value) {
            addCriterion("gmt_complete <>", value, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteGreaterThan(Date value) {
            addCriterion("gmt_complete >", value, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_complete >=", value, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteLessThan(Date value) {
            addCriterion("gmt_complete <", value, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteLessThanOrEqualTo(Date value) {
            addCriterion("gmt_complete <=", value, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteIn(List<Date> values) {
            addCriterion("gmt_complete in", values, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteNotIn(List<Date> values) {
            addCriterion("gmt_complete not in", values, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteBetween(Date value1, Date value2) {
            addCriterion("gmt_complete between", value1, value2, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andGmtCompleteNotBetween(Date value1, Date value2) {
            addCriterion("gmt_complete not between", value1, value2, "gmtComplete");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdIsNull() {
            addCriterion("payer_account_id is null");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdIsNotNull() {
            addCriterion("payer_account_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdEqualTo(String value) {
            addCriterion("payer_account_id =", value, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdNotEqualTo(String value) {
            addCriterion("payer_account_id <>", value, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdGreaterThan(String value) {
            addCriterion("payer_account_id >", value, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("payer_account_id >=", value, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdLessThan(String value) {
            addCriterion("payer_account_id <", value, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdLessThanOrEqualTo(String value) {
            addCriterion("payer_account_id <=", value, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdLike(String value) {
            addCriterion("payer_account_id like", value, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdNotLike(String value) {
            addCriterion("payer_account_id not like", value, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdIn(List<String> values) {
            addCriterion("payer_account_id in", values, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdNotIn(List<String> values) {
            addCriterion("payer_account_id not in", values, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdBetween(String value1, String value2) {
            addCriterion("payer_account_id between", value1, value2, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayerAccountIdNotBetween(String value1, String value2) {
            addCriterion("payer_account_id not between", value1, value2, "payerAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdIsNull() {
            addCriterion("payee_account_id is null");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdIsNotNull() {
            addCriterion("payee_account_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdEqualTo(String value) {
            addCriterion("payee_account_id =", value, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdNotEqualTo(String value) {
            addCriterion("payee_account_id <>", value, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdGreaterThan(String value) {
            addCriterion("payee_account_id >", value, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("payee_account_id >=", value, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdLessThan(String value) {
            addCriterion("payee_account_id <", value, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdLessThanOrEqualTo(String value) {
            addCriterion("payee_account_id <=", value, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdLike(String value) {
            addCriterion("payee_account_id like", value, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdNotLike(String value) {
            addCriterion("payee_account_id not like", value, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdIn(List<String> values) {
            addCriterion("payee_account_id in", values, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdNotIn(List<String> values) {
            addCriterion("payee_account_id not in", values, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdBetween(String value1, String value2) {
            addCriterion("payee_account_id between", value1, value2, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andPayeeAccountIdNotBetween(String value1, String value2) {
            addCriterion("payee_account_id not between", value1, value2, "payeeAccountId");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNull() {
            addCriterion("currency is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNotNull() {
            addCriterion("currency is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyEqualTo(String value) {
            addCriterion("currency =", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotEqualTo(String value) {
            addCriterion("currency <>", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThan(String value) {
            addCriterion("currency >", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("currency >=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThan(String value) {
            addCriterion("currency <", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThanOrEqualTo(String value) {
            addCriterion("currency <=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLike(String value) {
            addCriterion("currency like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotLike(String value) {
            addCriterion("currency not like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyIn(List<String> values) {
            addCriterion("currency in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotIn(List<String> values) {
            addCriterion("currency not in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyBetween(String value1, String value2) {
            addCriterion("currency between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotBetween(String value1, String value2) {
            addCriterion("currency not between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andTxntypeIsNull() {
            addCriterion("txnType is null");
            return (Criteria) this;
        }

        public Criteria andTxntypeIsNotNull() {
            addCriterion("txnType is not null");
            return (Criteria) this;
        }

        public Criteria andTxntypeEqualTo(String value) {
            addCriterion("txnType =", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeNotEqualTo(String value) {
            addCriterion("txnType <>", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeGreaterThan(String value) {
            addCriterion("txnType >", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeGreaterThanOrEqualTo(String value) {
            addCriterion("txnType >=", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeLessThan(String value) {
            addCriterion("txnType <", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeLessThanOrEqualTo(String value) {
            addCriterion("txnType <=", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeLike(String value) {
            addCriterion("txnType like", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeNotLike(String value) {
            addCriterion("txnType not like", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeIn(List<String> values) {
            addCriterion("txnType in", values, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeNotIn(List<String> values) {
            addCriterion("txnType not in", values, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeBetween(String value1, String value2) {
            addCriterion("txnType between", value1, value2, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeNotBetween(String value1, String value2) {
            addCriterion("txnType not between", value1, value2, "txntype");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andFailureReasonIsNull() {
            addCriterion("failure_reason is null");
            return (Criteria) this;
        }

        public Criteria andFailureReasonIsNotNull() {
            addCriterion("failure_reason is not null");
            return (Criteria) this;
        }

        public Criteria andFailureReasonEqualTo(String value) {
            addCriterion("failure_reason =", value, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonNotEqualTo(String value) {
            addCriterion("failure_reason <>", value, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonGreaterThan(String value) {
            addCriterion("failure_reason >", value, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonGreaterThanOrEqualTo(String value) {
            addCriterion("failure_reason >=", value, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonLessThan(String value) {
            addCriterion("failure_reason <", value, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonLessThanOrEqualTo(String value) {
            addCriterion("failure_reason <=", value, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonLike(String value) {
            addCriterion("failure_reason like", value, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonNotLike(String value) {
            addCriterion("failure_reason not like", value, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonIn(List<String> values) {
            addCriterion("failure_reason in", values, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonNotIn(List<String> values) {
            addCriterion("failure_reason not in", values, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonBetween(String value1, String value2) {
            addCriterion("failure_reason between", value1, value2, "failureReason");
            return (Criteria) this;
        }

        public Criteria andFailureReasonNotBetween(String value1, String value2) {
            addCriterion("failure_reason not between", value1, value2, "failureReason");
            return (Criteria) this;
        }

        public Criteria andDescIsNull() {
            addCriterion("desc is null");
            return (Criteria) this;
        }

        public Criteria andDescIsNotNull() {
            addCriterion("desc is not null");
            return (Criteria) this;
        }

        public Criteria andDescEqualTo(String value) {
            addCriterion("desc =", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotEqualTo(String value) {
            addCriterion("desc <>", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThan(String value) {
            addCriterion("desc >", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThanOrEqualTo(String value) {
            addCriterion("desc >=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThan(String value) {
            addCriterion("desc <", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThanOrEqualTo(String value) {
            addCriterion("desc <=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLike(String value) {
            addCriterion("desc like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotLike(String value) {
            addCriterion("desc not like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescIn(List<String> values) {
            addCriterion("desc in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotIn(List<String> values) {
            addCriterion("desc not in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescBetween(String value1, String value2) {
            addCriterion("desc between", value1, value2, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotBetween(String value1, String value2) {
            addCriterion("desc not between", value1, value2, "desc");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("direction is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("direction is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(String value) {
            addCriterion("direction =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(String value) {
            addCriterion("direction <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(String value) {
            addCriterion("direction >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("direction >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(String value) {
            addCriterion("direction <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(String value) {
            addCriterion("direction <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLike(String value) {
            addCriterion("direction like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotLike(String value) {
            addCriterion("direction not like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<String> values) {
            addCriterion("direction in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<String> values) {
            addCriterion("direction not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(String value1, String value2) {
            addCriterion("direction between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(String value1, String value2) {
            addCriterion("direction not between", value1, value2, "direction");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account_transaction
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 14 17:36:27 MYT 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account_transaction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}