package com.alipay.alipay_plus.common.dal.auto.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class AccountTransactionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.txn_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String txnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.gmt_create
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.gmt_modified
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.gmt_complete
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private Date gmtComplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.payer_account_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String payerAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.payee_account_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String payeeAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.amount
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.currency
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.txnType
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String txntype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.status
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.failure_reason
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String failureReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.desc
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_transaction.direction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    private String direction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.txn_id
     *
     * @return the value of account_transaction.txn_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.txn_id
     *
     * @param txnId the value for account_transaction.txn_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setTxnId(String txnId) {
        this.txnId = txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.gmt_create
     *
     * @return the value of account_transaction.gmt_create
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.gmt_create
     *
     * @param gmtCreate the value for account_transaction.gmt_create
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.gmt_modified
     *
     * @return the value of account_transaction.gmt_modified
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.gmt_modified
     *
     * @param gmtModified the value for account_transaction.gmt_modified
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.gmt_complete
     *
     * @return the value of account_transaction.gmt_complete
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public Date getGmtComplete() {
        return gmtComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.gmt_complete
     *
     * @param gmtComplete the value for account_transaction.gmt_complete
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setGmtComplete(Date gmtComplete) {
        this.gmtComplete = gmtComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.payer_account_id
     *
     * @return the value of account_transaction.payer_account_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getPayerAccountId() {
        return payerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.payer_account_id
     *
     * @param payerAccountId the value for account_transaction.payer_account_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setPayerAccountId(String payerAccountId) {
        this.payerAccountId = payerAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.payee_account_id
     *
     * @return the value of account_transaction.payee_account_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getPayeeAccountId() {
        return payeeAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.payee_account_id
     *
     * @param payeeAccountId the value for account_transaction.payee_account_id
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setPayeeAccountId(String payeeAccountId) {
        this.payeeAccountId = payeeAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.amount
     *
     * @return the value of account_transaction.amount
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.amount
     *
     * @param amount the value for account_transaction.amount
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.currency
     *
     * @return the value of account_transaction.currency
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.currency
     *
     * @param currency the value for account_transaction.currency
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.txnType
     *
     * @return the value of account_transaction.txnType
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getTxntype() {
        return txntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.txnType
     *
     * @param txntype the value for account_transaction.txnType
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setTxntype(String txntype) {
        this.txntype = txntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.status
     *
     * @return the value of account_transaction.status
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.status
     *
     * @param status the value for account_transaction.status
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.failure_reason
     *
     * @return the value of account_transaction.failure_reason
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getFailureReason() {
        return failureReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.failure_reason
     *
     * @param failureReason the value for account_transaction.failure_reason
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.desc
     *
     * @return the value of account_transaction.desc
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.desc
     *
     * @param desc the value for account_transaction.desc
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_transaction.direction
     *
     * @return the value of account_transaction.direction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_transaction.direction
     *
     * @param direction the value for account_transaction.direction
     *
     * @mbg.generated Sat Feb 14 17:36:27 MYT 2026
     */
    public void setDirection(String direction) {
        this.direction = direction;
    }
}