package com.alipay.account_center.common.dal.auto.daointerface;

import com.alipay.account_center.common.dal.auto.dataobject.AccountDO;
import com.alipay.account_center.common.dal.auto.dataobject.AccountDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    long countByExample(AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int deleteByExample(AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int insert(AccountDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int insertSelective(AccountDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    List<AccountDO> selectByExample(AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    AccountDO selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int updateByExampleSelective(@Param("row") AccountDO row, @Param("example") AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int updateByExample(@Param("row") AccountDO row, @Param("example") AccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int updateByPrimaryKeySelective(AccountDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int updateByPrimaryKey(AccountDO row);
}