package com.alipay.account_center.common.dal.auto.daointerface;

import com.alipay.account_center.common.dal.auto.dataobject.TransactionDO;
import com.alipay.account_center.common.dal.auto.dataobject.TransactionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    long countByExample(TransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int deleteByExample(TransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int deleteByPrimaryKey(String txnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int insert(TransactionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int insertSelective(TransactionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    List<TransactionDO> selectByExample(TransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    TransactionDO selectByPrimaryKey(String txnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int updateByExampleSelective(@Param("row") TransactionDO row, @Param("example") TransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int updateByExample(@Param("row") TransactionDO row, @Param("example") TransactionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int updateByPrimaryKeySelective(TransactionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Fri Mar 13 00:37:29 AEDT 2026
     */
    int updateByPrimaryKey(TransactionDO row);
}